%% GUI_Check_T1()
% LISCOMP Lab 2021 - 2022 https://liscomp.dima.unige.it
% -------------------------------------------------------------------------
% DESCRIPTION: 
% This function creates a GUI. With this GUI one can:
% - visualize the result of the level set segmentation for each slice of
%   the tumor (T1);
% - modify the mask in case it does not correspond exactly to the
%   tumor region.
% Sometimes the post processing in Segmentation_Analysis_brain produces
% another segmentation option. In this case one can choose the most
% accurate segmentation for that slice, and possibly modify it. It is 
% possible to scroll slices within the tumour volume using the buttons 
% 'Next slice' and 'Previous slice'. Once finished, click 'Done' in order 
% to save changes and continue with the radiomics analysis (T1).
% -------------------------------------------------------------------------
%%%% called by: Start_Analysis_brain()
%%%%            main_gui_brain(), button 'Check T1 segmentation'
%%%% call:  Show_ROI()
%%%%        Save_Last_Slice()
%%%%        Go_Previous_Slice()
%%%%        Go_Next_Slice()
%%%%        Slider_WindowDown_GUI_T1()
%%%%        Slider_WindowUp_GUI_T1()
%%%%        Slider_ContrastGUI_T1()
%%%%        Replace_With_previous_Slice()
%%%%        Replace_With_Next_Slice()

function GUI_Check_T1()

global pos
global gui_ROI
global ROI
global gui_T1

pos.FIGURE_test = pos.FIGURE - [10,25,0,0];
pos.PANEL_test = [5,5,pos.FIGURE_test(3)-5,pos.FIGURE_test(4)-5];
pos.TxtROI = [90,590,50,50].*pos.scale_factor;          
pos.TxtROI_val = [135,590,50,50].*pos.scale_factor;      
pos.TxtROIof = [170,590,40,50].*pos.scale_factor;       
pos.TxtROI_num = [200,590,50,50].*pos.scale_factor;    
pos.TxtSlice = [240,590,90,50].*pos.scale_factor;        
pos.TxtSlice_val = [305,590,50,50].*pos.scale_factor;    
pos.TxtSliceof = [340,590,40,50].*pos.scale_factor;      
pos.TxtSlice_num = [380,590,50,50].*pos.scale_factor;    
pos.ax = [-10,85,490,490].*pos.scale_factor;
pos.ax_ls = [350,85,490,490].*pos.scale_factor;
pos.ax_fwd = [710,85,490,490].*pos.scale_factor;
pos.SLIDERcontrast = round([10,85,25,490].*pos.scale_factor);
pos.SLIDERwindowUp_edit=round([5,630,80,25].*pos.scale_factor);
pos.SLIDERwindowDown_edit=round([5,50,80,25].*pos.scale_factor);
pos.SLIDERwindowUp_push=round([5,590,80,25].*pos.scale_factor);
pos.SLIDERwindowDown_push=round([5,10,80,25].*pos.scale_factor);

pos.replace_with_previous = [470,650,300,50].*pos.scale_factor;
pos.replace_with_next = [780,650,300,50].*pos.scale_factor;
pos.Radio_choice = [435,595,680,50].*pos.scale_factor;
pos.rb_ls = [80,0,50,50].*pos.scale_factor;
pos.rb_fwd = [530,0,150,50].*pos.scale_factor;
pos.Previous_slice = [350,15,180,50].*pos.scale_factor;
pos.Next_slice = [555,15,120,50].*pos.scale_factor;
pos.Done = [1000,15,120,50].*pos.scale_factor;

gui_T1.fig = figure('Position',pos.FIGURE_test,'Name','CHECK SLICES');
set(gui_T1.fig,'NumberTitle','off');
set(gui_T1.fig,'Color',gui_ROI.bgc_light);

gui_T1.panel=uipanel('parent',gui_T1.fig,'Title',...
    'Check MR images','units','pixel',...
    'Position',pos.PANEL_test,...
    'FontWeight','bold','FontSize',gui_ROI.fs,...
    'visible','on',...
    'BackGroundColor',gui_ROI.bgc_drop,...
    'ForeGroundColor',gui_ROI.fgc);

gui_T1.TxtROI = uicontrol('parent',gui_T1.panel,...
    'style', 'text',...
    'units', 'pixel',...
    'string', 'ROI',...
    'BackGroundColor',gui_ROI.bgc_drop,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'position', pos.TxtROI);

gui_T1.TxtROI_val = uicontrol('parent',gui_T1.panel,...
    'style', 'text',...
    'units', 'pixel',...
    'string', '1',...
    'BackGroundColor',gui_ROI.bgc_drop,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'position', pos.TxtROI_val);

gui_T1.TxtROIof = uicontrol('parent',gui_T1.panel,...     
    'style', 'text',...
    'units', 'pixel',...
    'string', 'of',...
    'BackGroundColor',gui_ROI.bgc_drop,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'position', pos.TxtROIof);

gui_T1.TxtROI_num = uicontrol('parent',gui_T1.panel,...     
    'style', 'text',...
    'units', 'pixel',...
    'string', '',...
    'BackGroundColor',gui_ROI.bgc_drop,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'position', pos.TxtROI_num);

gui_T1.TxtSlice = uicontrol('parent',gui_T1.panel,...
    'style', 'text',...
    'units', 'pixel',...
    'string', 'Slice',...
    'BackGroundColor',gui_ROI.bgc_drop,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'position', pos.TxtSlice);

gui_T1.TxtSlice_val = uicontrol('parent',gui_T1.panel,...
    'style', 'text',...
    'units', 'pixel',...
    'string', '1',...
    'BackGroundColor',gui_ROI.bgc_drop,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'position', pos.TxtSlice_val);

gui_T1.TxtSliceof = uicontrol('parent',gui_T1.panel,...     
    'style', 'text',...
    'units', 'pixel',...
    'string', 'of',...
    'BackGroundColor',gui_ROI.bgc_drop,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'position', pos.TxtSliceof);

gui_T1.TxtSlice_num = uicontrol('parent',gui_T1.panel,...    
    'style', 'text',...
    'units', 'pixel',...
    'string', '',...
    'BackGroundColor',gui_ROI.bgc_drop,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'position', pos.TxtSlice_num);

gui_T1.ax=axes('parent',gui_T1.panel,...
    'units','pixel',...
    'Title', 'Original',...
    'Position',pos.ax,...
    'xlim',[0.5 300.5],'ylim',[0.5 300.5]);

gui_T1.ax_ls=axes('parent',gui_T1.panel,...
    'units','pixel',...
    'Title', 'LS',...
    'Position',pos.ax_ls,...
    'xlim',[0.5 300.5],'ylim',[0.5 300.5]);

gui_T1.ax_fwd=axes('parent',gui_T1.panel,...
    'units','pixel',...
    'Title', 'Forward',...
    'Position',pos.ax_fwd,...
    'xlim',[0.5 300.5],'ylim',[0.5 300.5],...
    'Visible','off');

gui_T1.SLIDERcontrast = uicontrol(gui_T1.panel,...
    'Style','slider','Min',0,'Max',1,...
    'Value',gui_ROI.scale4contrast,'SliderStep',[0.01 0.05],...
    'units','pixel',...
    'position',pos.SLIDERcontrast,...
    'BackGroundColor',gui_ROI.bgc,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'enable','on',...
    'Callback','Slider_ContrastGUI_T1');

gui_T1.SLIDERwindowUp_edit=uicontrol(gui_T1.panel,'Style','edit',...
    'string',0,...
    'units','pixel',...
    'visible', 'on',...
    'position',pos.SLIDERwindowUp_edit,...
    'BackGroundColor',gui_ROI.bgc,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'enable','on');

gui_T1.SLIDERwindowDown_edit=uicontrol(gui_T1.panel,'Style','edit',...
    'string',0,...
    'units','pixel',...
    'visible', 'on',...
    'position',pos.SLIDERwindowDown_edit,...
    'BackGroundColor',gui_ROI.bgc,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'enable','on');

gui_T1.SLIDERwindowUp_push=uicontrol(gui_T1.panel,'Style','pushbutton',...
    'String','APPLY',...
    'units','pixel',...
    'position',pos.SLIDERwindowUp_push,...
    'BackGroundColor',gui_ROI.bgc,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'enable','on',...
    'callback', 'Slider_WindowUp_GUI_T1');

gui_T1.SLIDERwindowDown_push=uicontrol(gui_T1.panel,'Style','pushbutton',...
    'String','APPLY',...
    'units','pixel',...
    'position',pos.SLIDERwindowDown_push,...
    'BackGroundColor',gui_ROI.bgc,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'enable','on',...
    'callback', 'Slider_WindowDown_GUI_T1;');

gui_T1.replace_with_previous = uicontrol(gui_T1.panel,'style',...
    'pushbutton',...
    'units', 'pixel',...
    'string', 'Replace with previous slice',...
    'BackGroundColor',gui_ROI.bgc,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'enable','off',...
    'position',pos.replace_with_previous,...
    'callback', 'Replace_With_Previous_Slice;');

gui_T1.replace_with_next = uicontrol(gui_T1.panel,'style',...
    'pushbutton',...
    'units', 'pixel',...
    'string', 'Replace with next slice',...
    'BackGroundColor',gui_ROI.bgc,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'enable','on',...
    'position',pos.replace_with_next,...
    'callback', 'Replace_With_Next_Slice;');


gui_T1.Radio_choice = uibuttongroup(gui_T1.panel,...
    'units', 'pixel',...
     'position',pos.Radio_choice,...
     'BackGroundColor',gui_ROI.bgc_drop,...
     'ForeGroundColor',gui_ROI.bgc_drop,...
     'Visible','on');
 
gui_T1.rb_ls = uicontrol(gui_T1.Radio_choice,...
    'Style','radiobutton',...
    'units','pixel',...
    'Position',pos.rb_ls,...
    'String','1',...%ls - level set
    'Value',1,...
    'visible','on',...
    'BackGroundColor',gui_ROI.bgc_drop,...
    'FontSize',gui_ROI.fs, ...
    'HandleVisibility','on'); 

gui_T1.rb_fwd = uicontrol(gui_T1.Radio_choice,...
    'Style','radiobutton',...
    'units','pixel',...
    'Position',pos.rb_fwd,...
    'String','2',... %forward
    'BackGroundColor',gui_ROI.bgc_drop,...
    'FontSize',gui_ROI.fs,...
    'HandleVisibility','on');

set(gui_T1.Radio_choice,'Visible','on')
set(gui_T1.rb_fwd,'Visible','off')
gui_T1.Next_slice = uicontrol(gui_T1.panel,'style',...
    'pushbutton',...
    'units', 'pixel',...
    'string', 'Next slice',...
    'BackGroundColor',gui_ROI.bgc,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'enable','on',...
    'position',pos.Next_slice,...
    'callback', 'Go_Next_Slice;');

gui_T1.Previous_slice = uicontrol(gui_T1.panel,'style',...
    'pushbutton',...
    'units', 'pixel',...
    'string', 'Previous slice',...
    'BackGroundColor',gui_ROI.bgc,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'enable','off',...
    'position',pos.Previous_slice,...
    'callback', 'Go_Previous_Slice;');

gui_T1.Done = uicontrol(gui_T1.panel,'style',...
    'pushbutton',...
    'units', 'pixel',...
    'string', 'Done',...
    'BackGroundColor',gui_ROI.bgc,...
    'ForeGroundColor',gui_ROI.fgc,...
    'FontSize',gui_ROI.fs,...
    'enable','off',...
    'position',pos.Done,...
    'callback', 'Save_Last_Slice;');

gui_T1.first_opening=0;

gui_T1.idx_ROI_enabled = [];
for val = 1 : size(ROI,2)
    if ROI{val}.Enable
       gui_T1.idx_ROI_enabled = [gui_T1.idx_ROI_enabled, val];
    end
end
gui_T1.n_ROI = 1;
gui_T1.val = gui_T1.idx_ROI_enabled(gui_T1.n_ROI);
set(gui_T1.TxtROI_val,'string', num2str(gui_T1.val));

Nval = length(ROI);

for val = 1 : Nval

    if ROI{val}.Enable

        gui_T1.NumSlices{val} = ROI{val}.EndMR-ROI{val}.StartMR+1;
        gui_T1.SlicesList{val} = linspace(1,gui_T1.NumSlices{val},gui_T1.NumSlices{val});

        % If it's the first time
         if isempty(ROI{val}.SliceChoice)
            % If GUI_Check_T1 is opened fot the first time for a 
            % patient, then it initializes everything otherwise it leaves 
            % the pre-saved vectors unchanged. Set: 
            % ROI{val} = rmfield(ROI{val},'SliceChoice')
            % if new initialization is needed
            ROI{val}.first_next = zeros(1,gui_T1.NumSlices{val});   % this is needed for Show_ROI
            ROI{val}.SliceChoice = zeros(1,gui_T1.NumSlices{val});  % otherwise this is modified
        end
    end
end

% Set the number of ROIs and slices in the gui panel
set(gui_T1.TxtROI_num,'string', num2str(length(gui_T1.idx_ROI_enabled)));   
set(gui_T1.TxtSlice_num,'string', num2str(length(gui_T1.SlicesList{gui_T1.val})));   

gui_T1.k = 1;
gui_T1.it2show = gui_T1.SlicesList{gui_T1.val}(gui_T1.k);
Show_ROI(gui_T1.val,gui_T1.it2show)

